name: 'SockBoom Checkin Action'

on:
  schedule:
    - cron: '30 16 * * *' # UTC+8小时=北京时间 16代表零点
  watch:
    types: [started]
   
jobs:
  checking:
    runs-on: ubuntu-latest
    env:
        DOMAIN: https://sockboom.id
    if: >-
      github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai 
    - name: Checkout
      uses: actions/checkout@master
    - name: Login in APi #Api调用
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: | 
        curl -s -c cookie.txt -X POST "${DOMAIN}/auth/login" -d email="${EMAIL}" -d passwd="${PASSWORD}"
    - name: Checkin in Api #签到
      run: |
        dateTime=`date +%Y-%m-%d\ %H:%M:%S`
        response=$(curl -b cookie.txt -X POST "${DOMAIN}/user/checkin")
        rm -rf cookie.txt
        echo "$dateTime - $(echo -e ${response})" >> run.log
        tail run.log #避免日志上传失败丢失日志
    - name: Commit #上传日志到仓库
      env:
       NAME: abc97393094
       EMAIL: 97393094@qq.com
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add .
        git commit -m "update log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
